param (
    [string]$RepoOwner = "DeCEll-1",
    [string]$RepoName = "VramOptimizer"
)

$Token = $env:GITHUB_TOKEN
$Headers = @{
    "Accept"        = "application/vnd.github+json"
    "Authorization" = "Bearer $Token"
}

$Uri = "https://api.github.com/repos/$RepoOwner/$RepoName/releases"
try {
    $Releases = Invoke-RestMethod -Uri $Uri -Method Get -Headers $Headers -ErrorAction Stop
} catch {
    Write-Error "Failed to fetch releases from GitHub API: $_"
    exit 1
}

$SnapshotDate = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")

$LatestReleaseTag = if ($Releases.Count -gt 0) { $Releases[0].tag_name } else { $null }
$LatestPublishedAt = if ($Releases.Count -gt 0) { $Releases[0].published_at } else { $null }

$TotalRepoDownloads = 0
$PerFileDownloads = @()

foreach ($Release in $Releases) {

    $ReleaseSum = ($Release.assets | Measure-Object -Property download_count -Sum).Sum
    if ($null -ne $ReleaseSum) {
        $TotalRepoDownloads += $ReleaseSum
    }


    foreach ($Asset in $Release.assets) {
        $PerFileDownloads += [PSCustomObject]@{
            TagName            = $Release.tag_name
            FileName           = $Asset.name
            DownloadCount      = [int]$Asset.download_count
            ContentType        = $Asset.content_type
            BrowserDownloadUrl = $Asset.browser_download_url
        }
    }
}

$CurrentMetrics = [PSCustomObject]@{
    SnapshotDate    = $SnapshotDate
    ReleaseTag      = $LatestReleaseTag
    PublishedAt     = $LatestPublishedAt
    TotalDownloads  = [int]$TotalRepoDownloads
    AssetsBreakdown = $PerFileDownloads
}

$OutputPath = "./AutoGenerated/download_data.json"
$TargetDir = Split-Path $OutputPath -Parent
if (-not (Test-Path $TargetDir)) {
    New-Item -ItemType Directory -Path $TargetDir -Force | Out-Null
}

$HistoricalData = @()

if (Test-Path $OutputPath) {
    try {
    
        $RawJson = Get-Content -Raw -Path $OutputPath -ErrorAction Stop
        if (-not [string]::IsNullOrWhiteSpace($RawJson)) {
        
            $HistoricalData = ConvertFrom-Json $RawJson
        }
    } catch {
        Write-Warning "Existing JSON file was corrupt or unreadable. Starting fresh history tracking. Error: $_"
    }
}

$CombinedData = @($HistoricalData) + @($CurrentMetrics)

$CombinedData | ConvertTo-Json -Depth 10 | Out-File -FilePath $OutputPath -Encoding utf8

Write-Host "Successfully updated historical telemetry log at $OutputPath!"